### ISSUE TITLE
long_description=open("README.rst").read() cause UnicodeDecodeError

### ISSUE THREAD

**Issue by eromoe** [dfm/feedfinder2#4]
In python 3 win7 x64 chinese, 
detail

```
> pip install feedfinder2
Collecting feedfinder2
  Downloading http://mirrors.aliyun.com/pypi/packages/source/f/feedfinder2/feedfinder2-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\kasim\appdata\local\temp\pip-build-sapqnv\feedfinder2\setup.py", line 21, in <module>
        long_description=open("README.rst").read(),
    UnicodeDecodeError: 'gbk' codec can't decode bytes in position 161-162: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\kasim\appdata\local\temp\pip-build-sapqnv\feedfi
nder2
```

**Comment by dfm** [comment]
This should be fixed on pypi with version 0.0.2 and on the GitHub master. Give it a shot!

**Comment by eromoe** [comment]
I think you should not `import feedfinder2` before `setup()`,
because  six maybe hasn't installed yet.

```
> pip install https://github.com/dfm/feedfinder2/archive/master.zip
Collecting https://github.com/dfm/feedfinder2/archive/master.zip
  Downloading https://github.com/dfm/feedfinder2/archive/master.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\xxx\appdata\local\temp\pip-n2ao06-build\setup.py", line 8, in <module>
        import feedfinder2
      File "feedfinder2.py", line 12, in <module>
        from six.moves.urllib import parse as urlparse
    ImportError: No module named six.moves.urllib

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\xxx\appdata\local\temp\pip-n2ao06-build
```

**Comment by dfm** [comment]
This should be fixed now too. Sorry about not responding earlier!
